-- Run this in Supabase SQL Editor if production is behind the app.

ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS tax_id TEXT,
ADD COLUMN IF NOT EXISTS pdf_footer TEXT,
ADD COLUMN IF NOT EXISTS pdf_accent_color TEXT DEFAULT '#3B82F6',
ADD COLUMN IF NOT EXISTS pdf_template TEXT DEFAULT 'classic',
ADD COLUMN IF NOT EXISTS first_name TEXT,
ADD COLUMN IF NOT EXISTS last_name TEXT,
ADD COLUMN IF NOT EXISTS country TEXT,
ADD COLUMN IF NOT EXISTS city TEXT,
ADD COLUMN IF NOT EXISTS birth_date DATE,
ADD COLUMN IF NOT EXISTS avatar_url TEXT,
ADD COLUMN IF NOT EXISTS logo_onboarding_completed BOOLEAN DEFAULT false;

ALTER TABLE public.quotations
ADD COLUMN IF NOT EXISTS pdf_path TEXT,
ADD COLUMN IF NOT EXISTS pdf_generated_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS share_token TEXT,
ADD COLUMN IF NOT EXISTS sent_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS paid_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS signature_url TEXT;
